services:
  db:
    image: postgres:15-alpine
    container_name: voice_bot_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: bot_user
      POSTGRES_PASSWORD: bot_password
      POSTGRES_DB: voice_notes_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bot_user -d voice_notes_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: voice_bot_redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
  worker:
    build:
      context: .
      dockerfile: docker/Dockerfile.worker
    container_name: voice_bot_worker
    restart: unless-stopped
    env_file:
      - .env
    environment:
      # Перевизначаємо хости для роботи всередині Docker-мережі
      - REDIS_URL=redis://redis:6379/0
      - DB_URL=postgresql+asyncpg://bot_user:bot_password@db:5432/voice_notes_db
    volumes:
      - .:/app
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
    command: taskiq worker src.tasks.broker:broker src.tasks.tasks --reload

    
volumes:
  postgres_data:
  redis_data: